### ISSUE TITLE
Implementar Typescript

### ISSUE THREAD

**Issue by Muurilo** [FinotiLucas/Correios-Brasil#10]
O Typescript é um superset que está ficando cada vez mais popular, e com o aumento da popularidade do pacote parece ser uma boa hora para implementar ele. Ele vai dar inúmeras vantagens e produtividade para quem utilizar o pacote

**Comment by francopan** [comment]
Se quiser, estou disposto a implementar.

**Comment by Muurilo** [comment]
Seria otimo, eu não faço ideia porque o dono deu closed nessa issue.

**Comment by francopan** [comment]
Sim, teoricamente é simples. Basta criar o arquivo de tipo. correios-brasil.d.ts
Vou tentar fazer; Se conseguir, faço um branch e um pull request.
Estou trabalhando com a biblioteca em typescript e realmente ajudaria bastante.

**Comment by francopan** [comment]
Feita Pull Request com a feature implementada: https://github.com/FinotiLucas/Correios-Brasil/pull/11

**Comment by FinotiLucas** [comment]
Gente, bom dia. Eu já tenho ele quase pronto em TS, só falta atualizar algumas coisas e tbm está no mesmo padrão. Esse final de semana vou criar o brench com ele e vocês atualizam, se quiserem.

**Comment by jhsonmac** [comment]
> Gente, bom dia. Eu já tenho ele quase pronto em TS, só falta atualizar algumas coisas e tbm está no mesmo padrão. Esse final de semana vou criar o brench com ele e vocês atualizam, se quiserem.

Boa noite, blz? Alguma novidade com atualização para TS??
