### ISSUE TITLE
Arquivo de types não está sendo baixado pelo npm.

### ISSUE THREAD

**Issue by paulohcosta1** [FinotiLucas/Correios-Brasil#12]
Boa tarde, estou num projeto que usa typescript e quando tento usar a biblioteca de vcs, fala que não tem a tipagem, porém quando vejo aqui no repositório, o tipo está no projeto. Talvez o repositório do npm n esteja atualizado ?

Obrigado.

**Comment by FinotiLucas** [comment]
Bom dia Paulo, eu ainda não atualizei o pacote no npm !
Estou fazendo a migração do código inteiro de JS para TS  e acabei esquecendo de atualizar o suporte por lá, irei fazer isso o mais rápido possível... talvez hoje mesmo quando chegar do trabalho, qualquer atualização eu te aviso por aqui !
Obrigado por usar o pacote e de me atentar para esse problema, abraços.

**Comment by paulohcosta1** [comment]
Certo, estou no aguardo, obrigado!!

**Comment by FinotiLucas** [comment]
Paulo, tudo bem ? atualizei a versão do pacote no npm !
Qualquer coisa só falar, abraços !
