### ISSUE TITLE
Retorne mais dados no rastreio

### ISSUE THREAD

**Issue by pedrohenriquebraga** [FinotiLucas/Correios-Brasil#13]
Roterne na respostas do rastreio se o item foi entregue em uma variável, exemplo: `entregue: true`. Seria bem útil!
Parabéns pelo projeto maravilhoso!

**Comment by FinotiLucas** [comment]
Olá Pedro, obrigado pela força !
Vou tentar implementar essa funcionalidade em um próximo update, abraços !
