### ISSUE TITLE
Contato

### ISSUE THREAD

**Issue by dantearaujo** [FinotiLucas/Correios-Brasil#14]
Oi Lucas, Não sei se aqui é o melhor lugar, mas não encontrei suas informações de contato. Gostaria de bater um papo com você sobre a possibilidade de te contratar para um projeto que envolve a API dos Correios, poderia me chamar no Whatsapp? (84) 98168-1098

**Comment by FinotiLucas** [comment]
Obrigado pela mensagem Dante, estou fechando o problema pois já entrei em contato! 
Abraços.
