### ISSUE TITLE
Mixed Content HTTP/HTTPS

### ISSUE THREAD

**Issue by Michaeldrm** [FinotiLucas/Correios-Brasil#16]
E-commerce em produção HTTPS tem o conteúdo bloqueado pelo navegador ao tentar consultar preço e prazo no endereço: http://ws.correios.com.br/calculador/CalcPrecoPrazo.aspx

![Captura de tela 2021-03-28 194632](https://user-images.githubusercontent.com/4975044/112770802-c684f700-8ffe-11eb-8f20-7b39568e83dd.png)

**Comment by FinotiLucas** [comment]
Michael, muito obrigado por apontar o problema !
Acabei de enviar uma correção ao NPM, poderia verificar se o erro ainda persiste ?
Abraços.

**Comment by Michaeldrm** [comment]
Resolvido! Muito obrigado pela rápida resolução!
Abraços.

**Comment by FinotiLucas** [comment]
De nada ! Qualquer coisa só falar.

**Comment by Michaeldrm** [comment]
Infelizmente o erro agora é de CONNECTION TIMED OUT
![Captura de tela 2021-03-28 222403](https://user-images.githubusercontent.com/4975044/112775813-5bdeb600-9014-11eb-948e-662449102f17.png)
