### ISSUE TITLE
QUE LIB SENSACIONAL 😍 

### ISSUE THREAD

**Issue by filipedeschamps** [FinotiLucas/Correios-Brasil#23]
Uma sugestão: integrar a lib no [BrasilAPI](https://github.com/BrasilAPI/BrasilAPI) e disponibilizar também como um serviço na web 👍

**Comment by FinotiLucas** [comment]
### Filipe, muito obrigado pelo feedback !!!

É muito importante demais para mim, especialmente vindo de você pois fiz essa lib depois de assistir um vídeo seu...
Me rendeu até algumas aprovações em processos seletivos hahaha

**Comment by filipedeschamps** [comment]
hahahah que massa, parabéns!!! 😍  Bom, dada a sugestão, to fechando a issue 👍
