### ISSUE TITLE
Type 'RastreioEvent' is missing the following properties from type 'RastreioEvent[]'

### ISSUE THREAD

**Issue by hudson-bruno** [FinotiLucas/Correios-Brasil#24]
Na linha `ordersResponse = response[0];` ocorre o erro descrito no título, o typescript está acusando que o response é um `Array<RastreioEvent>` quando na verdade é um `Array<Array<RastreioEvent>>`, e isso pode ser comprovado no resultado do `console.log(response)`

```ts
rastrearEncomendas([code])
  .then((response) => {
    let ordersResponse: Array<RastreioEvent> = [];
  
    if (response) {
      // eslint-disable-next-line prefer-destructuring
      ordersResponse = response[0];
    }
  
    return console.log(response);
  })
  .catch((err) => console.log(err));
```
![image](https://user-images.githubusercontent.com/34108140/117549692-33ce7380-b012-11eb-8191-f5fe3be8747b.png)

Uma gambiarra temporária foi usar o código abaixo:
```ts
rastrearEncomendas([code])
  .then((response) => {
    let ordersResponse: Array<RastreioEvent> = [];
  
    if (response) {
      // eslint-disable-next-line prefer-destructuring
      ordersResponse = (response[0] as unknown) as Array<
                        RastreioEvent
                      >;
    }
  
    return console.log(response);
  })
  .catch((err) => console.log(err));
```
Tem algo que eu deixei passar ou isso é realmente um erro de tipagem da lib?

**Comment by FinotiLucas** [comment]
Fala, bom dia !

Vou dar uma olhada na tipagem aqui mas pode ser que tenha sido problema de implementação mesmo, obrigado !
