### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE] - rastrearEncomendas

### ISSUE THREAD

**Issue by gabrielfelipeio** [FinotiLucas/Correios-Brasil#26]
Olá! Estou tentando usar no Node.JS porem recebo o erro: TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be one of type string, Buffer, ArrayBuffer, Array, or Array-like Object. Received type object
Como faço pra utilizar no Node.js o pacote typescript?

Trecho do código:
```
const { rastrearEncomendas } = require('correios-brasil');

let codRastreio = ['NX132423096BR'];
rastrearEncomendas(codRastreio).then((response) => {
    console.log(response);
});
```

**Comment by FinotiLucas** [comment]
Seu código está correto, pode ser que não tenha instalado a Lib ou algum outro erro local.
Toda Lib em typescript é convertida para JS quando você instala então pode usar no node normalmente.

![image](https://user-images.githubusercontent.com/42899930/121446890-f0498b00-c96a-11eb-81ce-92edb2c9c4c9.png)
