### ISSUE TITLE
Problema com Cors no NextJS

### ISSUE THREAD

**Issue by mateus-werneck** [FinotiLucas/Correios-Brasil#28]
Estou tendo problemas com a função de `calcularPrecoPrazo()` . Testei a função de `consulterCep` e funcionou perfeitamente.  Alguma ideia de como resolver o problema?

No console aparece a mensagem `(motivo: falta cabeçalho 'Access-Control-Allow-Origin' no CORS)`.

![image](https://user-images.githubusercontent.com/25112157/142765727-57c45305-8674-429c-9bcc-e2955cfef634.png)

![image](https://user-images.githubusercontent.com/25112157/142765818-c8f876e4-93e8-456b-9858-8e3a3b6440cd.png)

**Comment by AdamTeodoroNunesDaSilva** [comment]
Para ocorrer esses tipos de problemas provavelmente você instalou a ferramenta no front-end, talvez de outros problemas como seu back-end seja https e a api dos correios http, nesse caso vc tem que fazer um proxy, ou seja usar essa ferramenta no seu back-end e receber os dados como cep, e tals do front-end, para que se mantenha seguro!!

**Comment by FinotiLucas** [comment]
Exatamente como o Adam Falou, o ideal seria fazer a consulta pelo backend ou utilizar um proxy.
Como não é um erro do projeto, vou fechar o problema.

Abraços.

**Comment by mateus-werneck** [comment]
Obrigado! =)
