### ISSUE TITLE
Presta atenção na formatação dos dados!!!!

### ISSUE THREAD

**Issue by AdamTeodoro** [FinotiLucas/Correios-Brasil#29]
Exemplo de retorno do git:
[ -->>>>>>>>>>>>>>>>>>>>>>>>>>>>ARRAY
  [
    {
      status: 'Objeto postado',
      data: '14/04/2020',
      hora: '14:28',
      local: 'AGF VILA PREL - Sao Paulo / SP',
    },
    {
      status: 'Objeto encaminhado',
      data: '15/04/2020',
      hora: '09:03',
      origem: 'AGF VILA PREL - Sao Paulo / SP',
      destino: 'CTE CAJAMAR - Cajamar / SP',
    },
    {
      status: 'Objeto encaminhado',
      data: '15/04/2020',
      hora: '22:18',
      origem: 'CTE CAJAMAR - Cajamar / SP',
      destino: 'CTE BENFICA - Rio De Janeiro / RJ',
    },
    {
      status: 'Objeto encaminhado',
      data: '16/04/2020',
      hora: '10:04',
      origem: 'CTE BENFICA - Rio De Janeiro / RJ',
      destino: 'CDD ITAGUAI - Itaguai / RJ',
    },
    {
      status: 'Objeto saiu para entrega ao destinatário',
      data: '17/04/2020',
      hora: '08:06',
      local: 'CDD ITAGUAI - Itaguai / RJ',
    },
    {
      status: 'Objeto entregue ao destinatário',
      data: '17/04/2020',
      hora: '11:12',
      local: 'CDD ITAGUAI - Itaguai / RJ',
    },
  ],
    [
      {
        status: 'Objeto postado após o horário limite da unidade',
        data: '05/05/2020',
        hora: '18:17',
        local: 'AGF CIDADE DAS ROSAS - Sapiranga / RS',
      },
      {
        status: 'Objeto encaminhado',
        data: '05/05/2020',
        hora: '18:29',
        origem: 'AGF CIDADE DAS ROSAS - Sapiranga / RS',
        destino: 'CTCE PORTO ALEGRE - Porto Alegre / RS',
      },
      {
        status: 'Objeto encaminhado',
        data: '09/05/2020',
        hora: '03:05',
        origem: 'CTE CAJAMAR - Cajamar / SP',
        destino: 'CTE BENFICA - Rio De Janeiro / RJ',
      },
      {
        status: 'Objeto encaminhado',
        data: '12/05/2020',
        hora: '13:54',
        origem: 'CTE BENFICA - Rio De Janeiro / RJ',
        destino: 'CDD ITAGUAI - Itaguai / RJ',
      },
      {
        status: 'Objeto saiu para entrega ao destinatário',
        data: '13/05/2020',
        hora: '10:18',
        local: 'CDD ITAGUAI - Itaguai / RJ',
      },
      {
        status: 'Objeto entregue ao destinatário',
        data: '13/05/2020',
        hora: '13:22',
        local: 'CDD ITAGUAI - Itaguai / RJ',
      },
    ];
]
Exemplo de retorno do medium:
{ // ->>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>OBJETO
  '0': [
    {
      status: 'Objeto postado',
      data: '14/04/2020',
      hora: '14:28',
      local: 'AGF VILA PREL - Sao Paulo / SP'     
    },
    {
      status: 'Objeto encaminhado',
      data: '15/04/2020',
      hora: '09:03',
      origem: 'AGF VILA PREL - Sao Paulo / SP',   
      destino: 'CTE CAJAMAR - Cajamar / SP'       
    },
    {
      status: 'Objeto encaminhado',
      data: '15/04/2020',
      hora: '22:18',
      origem: 'CTE CAJAMAR - Cajamar / SP',       
      destino: 'CTE BENFICA - Rio De Janeiro / RJ'
    },
    {
      status: 'Objeto encaminhado',
      data: '16/04/2020',
      hora: '10:04',
      origem: 'CTE BENFICA - Rio De Janeiro / RJ',
      destino: 'CDD ITAGUAI - Itaguai / RJ'
    },
    {
      status: 'Objeto saiu para entrega ao destinatário',
      data: '17/04/2020',
      hora: '08:06',
      local: 'CDD ITAGUAI - Itaguai / RJ'
    },
    {
      status: 'Objeto entregue ao destinatário',
      data: '17/04/2020',
      hora: '11:12',
      local: 'CDD ITAGUAI - Itaguai / RJ'
    },
    {
      status: 'Objeto entregue ao destinatário',
      data: '17/04/2020',
      hora: '11:12',
      local: 'CDD ITAGUAI - Itaguai / RJ'
    }
  ],
  '1': [
    {
      status: 'Objeto postado após o horário limite da unidade',
      data: '05/05/2020',
      hora: '18:17',
      local: 'AGF CIDADE DAS ROSAS - Sapiranga / RS'
    },
    {
      status: 'Objeto encaminhado',
      data: '05/05/2020',
      hora: '18:29',
      origem: 'AGF CIDADE DAS ROSAS - Sapiranga / RS',
      destino: 'CTCE PORTO ALEGRE - Porto Alegre / RS'
    },
    {
      status: 'Objeto encaminhado',
      data: '09/05/2020',
      hora: '03:05',
      origem: 'CTE CAJAMAR - Cajamar / SP',
      destino: 'CTE BENFICA - Rio De Janeiro / RJ'
    },
    {
      status: 'Objeto encaminhado',
      data: '12/05/2020',
      hora: '13:54',
      origem: 'CTE BENFICA - Rio De Janeiro / RJ',
      destino: 'CDD ITAGUAI - Itaguai / RJ'
    },
    {
      status: 'Objeto saiu para entrega ao destinatário',
      data: '13/05/2020',
      hora: '10:18',
      local: 'CDD ITAGUAI - Itaguai / RJ'
    },
    {
      status: 'Objeto entregue ao destinatário',
      data: '13/05/2020',
      hora: '13:22',
      local: 'CDD ITAGUAI - Itaguai / RJ'
    },
    {
      status: 'Objeto entregue ao destinatário',
      data: '13/05/2020',
      hora: '13:22',
      local: 'CDD ITAGUAI - Itaguai / RJ'
    }
  ]
}

**Comment by FinotiLucas** [comment]
Obrigado pelo aviso, o texto do Medium é de uma versão anterior a atual do projeto.
Atualizarei o texto no artigo.

**Comment by AdamTeodoro** [comment]
Eu que agradeço ;)
