### ISSUE TITLE
Unable to resolve module http

### ISSUE THREAD

**Issue by jhsonmac** [FinotiLucas/Correios-Brasil#31]
PROJETO\node_modules\correios-brasil\dist\index.js: http could not be found within the project or in these directories:
  node_modules\correios-brasil\node_modules
  node_modules

![Capturar](https://user-images.githubusercontent.com/38335699/143915732-cef82e13-206e-4afe-88ba-aaee3fee2425.PNG)

Erro esta sendo indicado nessa linha=>
"use strict";Object.defineProperty(exports,"__esModule",{value:!0});var e=require("node-fetch"),t=require("http"),r=require("https"),n=require("querystring"),o=require("iconv-lite"),a=require("xml-js"),c=require("cheerio");function i(e){return e&&"object"==typeof e&&"default"in e?e:{default:e}}var u=i(e),s=i(t),l=i(r),f=i(n),p=i(o),h=i(a),d=i(c);function v(e){var t=new RegExp(/[^0-9]|[/ /]/g,""),r=e.trim().replace(t,"");if(8!==r.length)throw Error("Cep: "+e+" inválido!");return r}

Limpei projeto, reinstalei todos pacotes mas sem sucesso com uso da Lib..

**Comment by mJR-exe** [comment]
O mesmo problema aqui...

**Comment by FinotiLucas** [comment]
Pessoal, boa tarde.
Vou refazer algumas partes do projeto nos próximos dias.
Creio que vai corrigir esses erros.

**Comment by VictorMello1993** [comment]
Já dei o meu jeito. Era só copiar essas linhas de libs no webpack da pasta da lib do ```react-scripts``` que fica dentro do pasta do ```node_modules```. É uma solução paliativa, mas pode voltar com os mesmos erros quando recompilar o create react app depois de adicionar novas dependências ao seu projeto.

Referência: https://stackoverflow.com/questions/70398678/i-tried-to-polyfill-modules-in-webpack-5-but-not-working-reactjs

**Comment by trindadematheus** [comment]
alguma att sobre?

**Comment by jhsonmac** [comment]
> Pessoal, boa tarde. Vou refazer algumas partes do projeto nos próximos dias. Creio que vai corrigir esses erros.

Parabéns pela lib @FinotiLucas, talvez queira usar endpoint do app correios também como alternativa. 
https://proxyapp.correios.com.br/v1/sro-rastro/${CODIGORASTREAMENTO}
tem funcionado sem problemas

**Comment by trindadematheus** [comment]
nessa api consigo passar mais de um codigo de vez? pra nao ter que fazer varias requests

**Comment by FinotiLucas** [comment]
@jhsonmac vou usar para montar a nova versão, muito obrigado !

**Comment by FinotiLucas** [comment]
Gente, atualizei o pacote !
Creio que o erro não deva acontecer mais pois modifiquei como as requests eram feitas.
Mas caso aconteça novamente creio que a melhor solução seria criar uma rota no backend que consuma os dados ao invés de usar direto no frontend.

@jhsonmac mudei o rastreio dessa nova versão para o proxyapp que você indicou, ficou bem mais completo do que era antes.
