### ISSUE TITLE
Dúvida com tratamento de exceção no calcularPrecoPrazo

### ISSUE THREAD

**Issue by whydea** [FinotiLucas/Correios-Brasil#36]
Olá!
Primeiramente parabéns pela lib, realmente é sensacional.

Estou com uma dúvida/problema para fazer tratamento de exceções na lib no método calcularPrecoPrazo.
Por exemplo quando eu passo um cep de destino inválido a lib gera uma exceção que o cep é inválido, porém pelo que eu vi não há um tratamento no reject na promisse, e acaba que não estou conseguindo capturar a exceção num try catch e minha aplicação fica travada.

Existe alguma outra maneira de realizar este tratamento para que eu consiga tratar as exceções?

**Comment by FinotiLucas** [comment]
@whydea, desculpe pela demora na resposta.
Problema foi corrigido na nova versão do pacote.
