### ISSUE TITLE
Algumas infos estão vindo duplicadas.

### ISSUE THREAD

**Issue by venanciosouza** [FinotiLucas/Correios-Brasil#4]
Olá pessoal! Tudo bem? Parabéns pelo projeto! Ficou muito bom.

Hoje peguei um pequeno bug. Aparentemente algumas informaçõse estão vindo duplicadas.

const { RastreioBrasil, CorreiosBrasil } = require("correios-brasil");
correios = new RastreioBrasil("pw750668763br")
correios.rastrearEncomendas().then(console.log)

// log
 events: [
    {
      status: 'Status: Objeto encaminhado ',
      data: 'Data  : 08/07/2020 | Hora: 14:59',
      origem: 'Origem: CTE CAJAMAR - Cajamar / SP',
      destino: 'Destino: CDD IMPERATRIZ - Imperatriz / MA'
    },
    {
      status: 'Status: Objeto encaminhado ',
      data: 'Data  : 08/07/2020 | Hora: 14:59',
      origem: 'Origem: CTE CAJAMAR - Cajamar / SP',
      destino: 'Destino: CDD IMPERATRIZ - Imperatriz / MA'
    }
]

De já, obrigado!

**Comment by FinotiLucas** [comment]
Verdade, a primeira e a segunda posição sempre vem iguais por conta do formato do site dos correios.
Obrigado por me informar isso, irei corrigir esse problema ! Enquanto isso, olhe a documentação e atualize a lib para a versão 2.0, lá você pode fazer o rastreio de múltiplas encomendas.
Abraços.
