### ISSUE TITLE
Erro ao rastrearEncomendas

### ISSUE THREAD

**Issue by Da-ntas** [FinotiLucas/Correios-Brasil#42]
Código:
```
const ch = ['OX639154242BR'];

rastrearEncomendas(ch).then(response => {console.log(response.response);}).catch((err) => console.log(err.response))
```

Retorno:
```
{
  status: 403,
  statusText: 'Forbidden',
  headers: {
    date: 'Fri, 14 Oct 2022 13:10:56 GMT',
    'content-type': 'application/json',
    'transfer-encoding': 'chunked',
    connection: 'close',
    expires: '0',
    'cache-control': 'no-cache, no-store, max-age=0, must-revalidate',
    'x-xss-protection': '1; mode=block',
    pragma: 'no-cache',
    'x-frame-options': 'DENY',
    'x-content-type-options': 'nosniff',
    'strict-transport-security': 'max-age=15724800; includeSubDomains',
    'set-cookie': [
      'LBprdint1=238747658.47873.0000; path=/; Httponly; Secure',
      'f5avraaaaaaaaaaaaaaaa_session_=BBPKMCMPEKADJKFMDHFCFOFKAGEPDLKDKPICKGLLONEBGKJLDAOLBJLEEPOLJLLDKLIDDJMIFPCPLBBCHBEACAJCJFFMJKKLPADKGOFEMKFCEOMFMNIOGDDLDBGNNBDM; HttpOnly; secure',
      'LBprdExt1=633864202.47873.0000; path=/; Httponly; Secure'
    ]
  },
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [Function: httpAdapter],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    env: { FormData: [Function] },
    validateStatus: [Function: validateStatus],
    headers: {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'application/json',
      'User-Agent': 'axios/0.27.2'
    },
    method: 'get',
    url: 'https://proxyapp.correios.com.br/v1/sro-rastro/OX639154242BR',
    data: undefined
  },
  request: <ref *1> ClientRequest {
    _events: [Object: null prototype] {
      abort: [Function (anonymous)],
      aborted: [Function (anonymous)],
      connect: [Function (anonymous)],
      error: [Function (anonymous)],
      socket: [Function (anonymous)],
      timeout: [Function (anonymous)],
      prefinish: [Function: requestOnPrefinish]
    },
    _eventsCount: 7,
    _maxListeners: undefined,
    outputData: [],
    outputSize: 0,
    writable: true,
    destroyed: false,
    _last: true,
    chunkedEncoding: false,
    shouldKeepAlive: false,
    maxRequestsOnConnectionReached: false,
    _defaultKeepAlive: true,
    useChunkedEncodingByDefault: false,
    sendDate: false,
    _removedConnection: false,
    _removedContLen: false,
    _removedTE: false,
    _contentLength: 0,
    _hasBody: true,
    _trailer: '',
    finished: true,
    _headerSent: true,
    _closed: false,
    socket: TLSSocket {
      _tlsOptions: [Object],
      _secureEstablished: true,
      _securePending: false,
      _newSessionPending: false,
      _controlReleased: true,
      secureConnecting: false,
      _SNICallback: null,
      servername: 'proxyapp.correios.com.br',
      alpnProtocol: false,
      authorized: true,
      authorizationError: null,
      encrypted: true,
      _events: [Object: null prototype],
      _eventsCount: 10,
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'proxyapp.correios.com.br',
      _readableState: [ReadableState],
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: undefined,
      _server: null,
      ssl: [TLSWrap],
      _requestCert: true,
      _rejectUnauthorized: true,
      parser: null,
      _httpMessage: [Circular *1],
      [Symbol(res)]: [TLSWrap],
      [Symbol(verified)]: true,
      [Symbol(pendingSession)]: null,
      [Symbol(async_id_symbol)]: 5,
      [Symbol(kHandle)]: [TLSWrap],
      [Symbol(kSetNoDelay)]: false,
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(connect-options)]: [Object],
      [Symbol(RequestTimeout)]: undefined
    },
    _header: 'GET /v1/sro-rastro/OX639154242BR HTTP/1.1\r\n' +
      'Accept: application/json, text/plain, */*\r\n' +
      'Content-Type: application/json\r\n' +
      'User-Agent: axios/0.27.2\r\n' +
      'Host: proxyapp.correios.com.br\r\n' +
      'Connection: close\r\n' +
      '\r\n',
    _keepAliveTimeout: 0,
    _onPendingData: [Function: nop],
    agent: Agent {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      defaultPort: 443,
      protocol: 'https:',
      options: [Object: null prototype],
      requests: [Object: null prototype] {},
      sockets: [Object: null prototype],
      freeSockets: [Object: null prototype] {},
      keepAliveMsecs: 1000,
      keepAlive: false,
      maxSockets: Infinity,
      maxFreeSockets: 256,
      scheduling: 'lifo',
      maxTotalSockets: Infinity,
      totalSocketCount: 1,
      maxCachedSessions: 100,
      _sessionCache: [Object],
      [Symbol(kCapture)]: false
    },
    socketPath: undefined,
    method: 'GET',
    maxHeaderSize: undefined,
    insecureHTTPParser: undefined,
    path: '/v1/sro-rastro/OX639154242BR',
    _ended: true,
    res: IncomingMessage {
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 4,
      _maxListeners: undefined,
      socket: [TLSSocket],
      httpVersionMajor: 1,
      httpVersionMinor: 1,
      httpVersion: '1.1',
      complete: true,
      rawHeaders: [Array],
      rawTrailers: [],
      aborted: false,
      upgrade: false,
      url: '',
      method: null,
      statusCode: 403,
      statusMessage: 'Forbidden',
      client: [TLSSocket],
      _consuming: true,
      _dumped: false,
      req: [Circular *1],
      responseUrl: 'https://proxyapp.correios.com.br/v1/sro-rastro/OX639154242BR',
      redirects: [],
      [Symbol(kCapture)]: false,
      [Symbol(kHeaders)]: [Object],
      [Symbol(kHeadersCount)]: 28,
      [Symbol(kTrailers)]: null,
      [Symbol(kTrailersCount)]: 0,
      [Symbol(RequestTimeout)]: undefined
    },
    aborted: false,
    timeoutCb: null,
    upgradeOrConnect: false,
    parser: null,
    maxHeadersCount: null,
    reusedSocket: false,
    host: 'proxyapp.correios.com.br',
    protocol: 'https:',
    _redirectable: Writable {
      _writableState: [WritableState],
      _events: [Object: null prototype],
      _eventsCount: 3,
      _maxListeners: undefined,
      _options: [Object],
      _ended: true,
      _ending: true,
      _redirectCount: 0,
      _redirects: [],
      _requestBodyLength: 0,
      _requestBodyBuffers: [],
      _onNativeResponse: [Function (anonymous)],
      _currentRequest: [Circular *1],
      _currentUrl: 'https://proxyapp.correios.com.br/v1/sro-rastro/OX639154242BR',
      [Symbol(kCapture)]: false
    },
    [Symbol(kCapture)]: false,
    [Symbol(kNeedDrain)]: false,
    [Symbol(corked)]: 0,
    [Symbol(kOutHeaders)]: [Object: null prototype] {
      accept: [Array],
      'content-type': [Array],
      'user-agent': [Array],
      host: [Array]
    }
  },
  data: {
    msgs: [ 'Forbidden' ],
    date: '2022-10-14T10:10:56',
    causa: 'Forbidden',
    path: '/v1/sro-rastro/OX639154242BR'
  }
}
```

**Comment by altendorfme** [comment]
Correios encerrou o acesso aberto a rota (https://proxyapp.correios.com.br/), agora tem que fazer um pedido no https://cws.correios.com.br/.

Eles fornecem novas rotas `api.correios.com.br` que responde igual ao `proxyapp.correios.com.br`, mas antes tem que gerar um token e ter alguns acesso. Todo pedido pode demorar um pouco.

**Comment by ricardopereirasilveira** [comment]
Alguém conseguiu usar a API dos Correios ? Não estou conseguindo usar a API mais que não requer autenticação.

**Comment by altendorfme** [comment]
> Alguém conseguiu usar a API dos Correios ? Não estou conseguindo usar a API mais que não requer autenticação.

Foi desativada, parece conseguir o acesso ao webservice (https://cws.correios.com.br/) precisa fazer um registro no https://www.correios.com.br/correios-facil/correios-facil com o contrato no modelo Bronze.

**Comment by ivanseidel** [comment]
Fala pessoal. Consegui corrigir a biblioteca, para funcionar com o novo update. Vejam o PR #43. Nenhuma breaking change existe, e continua funcionando normalmente como antes com o patch.

Abraços!

**Comment by altendorfme** [comment]
> Fala pessoal. Consegui corrigir a biblioteca, para funcionar com o novo update. Vejam o PR #43. Nenhuma breaking change existe, e continua funcionando normalmente como antes com o patch.
> 
> Abraços!

Pra testar eu adaptei sua logica em outro script aqui e funcionou perfeitamente, mas qual a chance do `REQUEST_TOKEN` trocar no futuro?

**Comment by ivanseidel** [comment]
eu precisava disso ASAP, e publiquei no npm como `correios-brasil2`. Se quiser testar também, é só rodar `yarn test` (criei um test suite pra ele).

A chance disso trocar eu não sei, só vamos saber com o tempo... mas deve ser a mesma chance deles mudarem algo no app: 1 vez a cada 1-2 anos talvez?

Pelo que debuguei/fiz de engenharia reversa, esse token é fixo independente do dispositivo ou instalação do app. Por isso coloquei como fixo no código, realmente parece ser "uma chave" privada (que é pública rs)

**Comment by ricardopereirasilveira** [comment]
@ivanseidel & @altendorfme pelo que eu analisei o PR #43 vocês fizeram apenas um post na URL 'https://proxyapp.correios.com.br/v1/app-validation' mandando como parâmetro no corpo o token que esta na variável "REQUEST_TOKEN", e em seguida, o json retorna o Token e vocês guardam ele para usar no header na URL "PROXYAPP_RASTREAR", certo? Porque tentei fazer isto aqui por fora, e não consegui, conseguem confirmar se foram feito apenas esses passos mesmo ou se me perdi no PR rs.

**Comment by altendorfme** [comment]
> @ivanseidel & @altendorfme pelo que eu analisei o PR #43 vocês fizeram apenas um post na URL 'https://proxyapp.correios.com.br/v1/app-validation' mandando como parâmetro no corpo o token que esta na variável "REQUEST_TOKEN", e em seguida, o json retorna o Token e vocês guardam ele para usar no header na URL "PROXYAPP_RASTREAR", certo? Porque tentei fazer isto aqui por fora, e não consegui, conseguem confirmar se foram feito apenas esses passos mesmo ou se me perdi no PR rs.

Postman: https://red-sunset-863561.postman.co/workspace/My-Workspace~1453eb33-9aa8-469f-8c30-46ced27af5fb/collection/3209793-ed0ec8d9-f252-48a9-ac9f-0af875cbb80c?action=share&creator=3209793

**Comment by ricardopereirasilveira** [comment]
> > @ivanseidel & @altendorfme pelo que eu analisei o PR #43 vocês fizeram apenas um post na URL 'https://proxyapp.correios.com.br/v1/app-validation' mandando como parâmetro no corpo o token que esta na variável "REQUEST_TOKEN", e em seguida, o json retorna o Token e vocês guardam ele para usar no header na URL "PROXYAPP_RASTREAR", certo? Porque tentei fazer isto aqui por fora, e não consegui, conseguem confirmar se foram feito apenas esses passos mesmo ou se me perdi no PR rs.
> 
> Postman: https://red-sunset-863561.postman.co/workspace/My-Workspace~1453eb33-9aa8-469f-8c30-46ced27af5fb/collection/3209793-ed0ec8d9-f252-48a9-ac9f-0af875cbb80c?action=share&creator=3209793

solicitei acesso ai

**Comment by altendorfme** [comment]
> solicitei acesso ai @altendorfme, se conseguir autorizar para eu verificar :D

Atualizei a URL do post original para um projeto publico no Postman.

**Comment by ivanseidel** [comment]
> @ivanseidel & @altendorfme pelo que eu analisei o PR #43 vocês fizeram apenas um post na URL 'https://proxyapp.correios.com.br/v1/app-validation' mandando como parâmetro no corpo o token que esta na variável "REQUEST_TOKEN", e em seguida, o json retorna o Token e vocês guardam ele para usar no header na URL "PROXYAPP_RASTREAR", certo? Porque tentei fazer isto aqui por fora, e não consegui, conseguem confirmar se foram feito apenas esses passos mesmo ou se me perdi no PR rs.

O lance principal, é usar o `user-agent: Dart/2.18 (dart:io)` e o token é um header não-formal: `app-check-token: {token-sem-bearer-nem-nada}`

Se você estiver fazendo requisições do frontend, pode ser que ele esteja impedido de enviar o header `app-check-token` por `CORS` (você deve perceber o envio de um request `OPTIONS` como comportamento). De fato, é impossível utilizar essa API diretamente do front sem um backend de proxy. É esse o caso?

**Comment by ricardopereirasilveira** [comment]
> > solicitei acesso ai @altendorfme, se conseguir autorizar para eu verificar :D
> 
> Atualizei a URL do post original para um projeto publico no Postman.

muito obrigado



> > @ivanseidel & @altendorfme pelo que eu analisei o PR #43 vocês fizeram apenas um post na URL 'https://proxyapp.correios.com.br/v1/app-validation' mandando como parâmetro no corpo o token que esta na variável "REQUEST_TOKEN", e em seguida, o json retorna o Token e vocês guardam ele para usar no header na URL "PROXYAPP_RASTREAR", certo? Porque tentei fazer isto aqui por fora, e não consegui, conseguem confirmar se foram feito apenas esses passos mesmo ou se me perdi no PR rs.
> 
> O lance principal, é usar o `user-agent: Dart/2.18 (dart:io)` e o token é um header não-formal: `app-check-token: {token-sem-bearer-nem-nada}`
> 
> Se você estiver fazendo requisições do frontend, pode ser que ele esteja impedido de enviar o header `app-check-token` por `CORS` (você deve perceber o envio de um request `OPTIONS` como comportamento). De fato, é impossível utilizar essa API diretamente do front sem um backend de proxy. É esse o caso?

Não é o meu caso não, testei em Python e funcionou 100%. Vou usar em um APP agora que estou terminando de desenvolver em Flutter, colocando os devidos créditos, muito obrigado.!

**Comment by FinotiLucas** [comment]
@ivanseidel muito obrigado pela contribuição, estava sem tempo para verificar a correção deste problema.
Já testei por aqui e tudo certo, dei o Merge e subi uma nova versão no NPM.

Obrigado a todos.
