### ISSUE TITLE
Token de acesso aos correios

### ISSUE THREAD

**Issue by joao-uefrom** [FinotiLucas/Correios-Brasil#44]
Muitooo legal a sua lib, acabei esbarrando nela sem querer tentando achar uma resposta de como conseguir o token para receber os dados diretamente dos correios. Procurei muito e descobri que vc conseguiu um! Vc pode dar um norte de como conseguir esse token? A documentação dos correios é um tanto confusa, não encontrei muito sobre na internet e eu gostaria de ter meu próprio token para usar em um projeto meu que não é em js...

**Comment by altendorfme** [comment]
Tá explica em outra issue:

https://github.com/FinotiLucas/Correios-Brasil/issues/42#issuecomment-1301626497
