### ISSUE TITLE
O que seria o "requestToken"?

### ISSUE THREAD

**Issue by betomazela** [FinotiLucas/Correios-Brasil#45]
Poderia compartilhar como faço para obter o "requestToken" utilizado na operação "https://proxyapp.correios.com.br/v1/app-validation"?
Verifiquei que está fixo no código na constante REQUEST_TOKEN, mas gostaria de ter o meu próprio.

Obrigada!

**Comment by FinotiLucas** [comment]
Da uma olhada no #42, explica quase tudo lá.
