### ISSUE TITLE
Tracker correios credentials change

### ISSUE THREAD

**Issue by jhowbhz** [FinotiLucas/Correios-Brasil#52]
I have provisionally arranged the new credentials this commit #51

**Comment by jhowbhz** [comment]
Change keys again, WTF!

this a new key:

```json
{
  "requestToken": "YW5kcm9pZDtici5jb20uY29ycmVpb3MucHJlYXRlbmRpbWVudG87RjMyRTI5OTc2NzA5MzU5ODU5RTBCOTdGNkY4QTQ4M0I5Qjk1MzU3ODs1LjEuMTQ=",
  "data": "04/07/2023 16:24:07",
  "sign": "b2f79781672853e0e28c28db776cefe8"
}
```

**Comment by ferezini** [comment]
consegue novamente? mas não sei se será mto util parece q agora expira em 1 dia.

**Comment by andersonmendess** [comment]
> consegue novamente? mas não sei se será mto util parece q agora expira em 1 dia.

`{
  "requestToken": "YW5kcm9pZDtici5jb20uY29ycmVpb3MucHJlYXRlbmRpbWVudG87RjMyRTI5OTc2NzA5MzU5ODU5RTBCOTdGNkY4QTQ4M0I5Qjk1MzU3ODs1LjEuMTQ=",
  "data": "06/07/2023 09:03:01",
  "sign": "2bffecc02961980df437008cb7ca714f"
}`

**Comment by jhowbhz** [comment]
> consegue novamente? mas não sei se será mto util parece q agora expira em 1 dia.

```{
  "requestToken": "YW5kcm9pZDtici5jb20uY29ycmVpb3MucHJlYXRlbmRpbWVudG87RjMyRTI5OTc2NzA5MzU5ODU5RTBCOTdGNkY4QTQ4M0I5Qjk1MzU3ODs1LjEuMTQ=",
  "data": "05/07/2023 20:40:22",
  "sign": "a4a8704bf7275b4580eb42fdea11b3d9"
}```

Claro, ta na mão.....
Poderiamos criar um repo tipo assim.... https://hospedagem.com/chave.json

Ai a gente, consumiria esse arquivo de 1 unico local, atualizou 1, atualizou pra todos....
