### ISSUE TITLE
help

### ISSUE THREAD

**Issue by DeividAlmeida** [FinotiLucas/Correios-Brasil#6]
Oi Lucas, essa ferramenta é ótima, eu estou com um probleminha, se vc puder me ajudar, eu instalei tudo certinho, porém o js não roda nada no meu terminal.

![image](https://user-images.githubusercontent.com/46359732/87827833-0d0c3a00-c852-11ea-9473-6bcedd78b4b2.png)

**Comment by FinotiLucas** [comment]
Você iniciou os args dentro da classe , tenta fazer como eu fiz aqui em baixo que é sucesso.
abraços !

``` javascript
const { CorreiosBrasil } = require("correios-brasil"); 

let  args = {
  // Não se preocupe com a formatação dos valores de entrada do cep, qualquer uma será válida (ex: 21770-200, 21770 200, 21asa!770@###200 e etc),
  sCepOrigem:  "81200100",
  sCepDestino:  "21770200",
  nVlPeso:  "1",
  nCdFormato:  "1",
  nVlComprimento:  "20",
  nVlAltura:  "20",
  nVlLargura:  "20",
  nCdServico:  "04014",
  nVlDiametro:  "0",
};

correios = new  CorreiosBrasil(); 

correios.calcPrecoPrazo(args).then((response) => {
  console.log(response);
});
```

**Comment by DeividAlmeida** [comment]
![image](https://user-images.githubusercontent.com/46359732/87829083-a9374080-c854-11ea-94e0-a8f64a578e7c.png)

**Comment by DeividAlmeida** [comment]
agradeço pela rapida resposta, mas deu no mesmo

**Comment by DeividAlmeida** [comment]
será que o problema e no servidor dos correios?

**Comment by FinotiLucas** [comment]
Você clonou o repositório ou é um projeto novo ? eu criei um novo aqui e funcionou normalmente, se você clonou direto do git da um ```npm i``` no terminal e vê se funciona

**Comment by FinotiLucas** [comment]
![2020-07-17 (1)](https://user-images.githubusercontent.com/42899930/87830417-5743ea00-c857-11ea-8363-df224f849bb7.png)

**Comment by DeividAlmeida** [comment]
![image](https://user-images.githubusercontent.com/46359732/87831274-75124e80-c859-11ea-96b2-044b2dbe859b.png)

eu baixei o repositório

**Comment by DeividAlmeida** [comment]
![image](https://user-images.githubusercontent.com/46359732/87831301-852a2e00-c859-11ea-9aa7-da166836ab40.png)

**Comment by DeividAlmeida** [comment]
instalei 
![image](https://user-images.githubusercontent.com/46359732/87831397-c7536f80-c859-11ea-8815-6d4e8a170e93.png)

**Comment by DeividAlmeida** [comment]
![Capturar](https://user-images.githubusercontent.com/46359732/87831459-f1a52d00-c859-11ea-97b1-7b190b8bd618.PNG)

**Comment by DeividAlmeida** [comment]
agora foi obrigado

**Comment by DeividAlmeida** [comment]
Perdão, só mais uma pergunta, como eu faço para inputar essa informações em um html?  Sou novato em node.js
