### ISSUE TITLE
Dúvidas sobre cálculo e rastreamento

### ISSUE THREAD

**Issue by vitordhers** [FinotiLucas/Correios-Brasil#8]
Primeiramente gostaria de agradecer à iniciativa do projeto. Procurei há alguns meses essas soluções e encontrei parcialmente.
Dei uma lida rápida na documentação e surgiram algumas dúvidas:

**1.** Em relação ao cálculo de preços e prazos, vocês pensam em implementar o cálculo para mais de um serviço(exemplo, SEDEX e PAC), simultaneamente?

**2.** Em relação ao rastreamento, existe a possibilidade de haver retorno do status dos eventos devidamente listados no _item 13_ do manual de rastreamento dos correios ( [https://www.correios.com.br/enviar-e-receber/precisa-de-ajuda/manual_rastreamentoobjetosws.pdf](url) )?

Desde já obrigado e parabéns pela iniciativa.

**Comment by FinotiLucas** [comment]
1. Sim, já estou desenvolvendo exatamente essa funcionalidade, além de pegar informações para múltiplos números de CEPS.

2. Não, nessa lib eu não usei o esse sistema de rastreamento dos correios, mas sim o disponível no 'https://www.linkcorreios.com.br', pois para alguns casos, embora fosse mais completo teria que ter autenticação então essa forma foi a mais 'simples' de entregar uma solução semelhante, embora eu ainda sim vá implementar a que você apontou, na verdade já tenho implementado mas falta tempo para deixar com o mesmo padrão de código atual e integrar ao pacote.
